### ISSUE TITLE
Please upload API Source code / Response 

### ISSUE THREAD

**Issue by Afaquejaya** [sauravmunankarmi/Server-Driven-UI-Android#1]
Please upload response or API source code or save json response in android project and use it that json file from shared pref to display in the mainactivity.

**Comment by sauravmunankarmi** [comment]
Source code for backend is here: https://github.com/sauravmunankarmi/Server-Driven-UI-Spring
I have also uploaded a txt file with the example response.
Filename: json response example.txt
